name: CleanroomGenerator
main: net.neo_vortex.bukkit.CleanroomGenerator.CleanroomGenerator
version: 0.0.2
website: http://www.neo-vortex.net/
author: NVX
description: Custom world generator to generate flat clean rooms. y==0 is bedrock layer=height,block generator id=layer[,layer[,...]]
load: startup
