name: CleanroomGenerator
main: net.neo_vortex.bukkit.CleanroomGenerator.CleanroomGenerator
version: 0.0.1
website: http://www.neo-vortex.net/
author: NVX
description: Custom world generator to generate flat clean rooms. y==0 is bedrock, y>0 to y<height is block for generator id "height,block", or "64,1" by default
load: startup
