main: io.nv.bukkit.CleanroomGenerator.CleanroomGenerator
name: ${project.artifactId}
version: ${project.version}
website: ${plugin.website}
author: ${plugin.author}
description: ${project.description}
load: STARTUP
